import fs from 'node:fs';
import path from 'node:path';
import { canonicalize } from '../jcs.mjs';
import { sha256Hex } from '../hash.mjs';
import { verifyStateSnapshot } from '../v9/state.mjs';

export const GITHUB_READ_SURFACE_FORMAT='kristal.github-read-surface/1.0';
export const GITHUB_SYNC_MANIFEST_FORMAT='kristal.github-sync-manifest/1.0';
export const GITHUB_COLLECTION_INDEX_FORMAT='kristal.github-collection-index/1.0';
const DIGEST=/^sha256:[0-9a-f]{64}$/;
const SYNC_MANIFEST_REL='.kristal/sync-manifest.json';
const INDEX_REL='kristals/index.json';
function isObject(v){return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function nonEmpty(v){return typeof v==='string'&&v.length>0;}
function issue(issues,path_,message,code='INVALID_DOCUMENT'){issues.push({path:path_,code,message});}
function commitmentOk(c){return isObject(c)&&nonEmpty(c.profile)&&DIGEST.test(c.digest??'');}
function safeRel(v){if(!nonEmpty(v)||v.includes('\\'))return false; if(path.posix.isAbsolute(v))return false; const parts=v.split('/');return parts.every(x=>x&&x!=='.'&&x!=='..');}
function rootForSlug(slug){return `kristals/${slug}`;}
function utf8Compare(a,b){return Buffer.compare(Buffer.from(String(a),'utf8'),Buffer.from(String(b),'utf8'));}
function codePointCompare(a,b){const aa=Array.from(String(a),c=>c.codePointAt(0));const bb=Array.from(String(b),c=>c.codePointAt(0));for(let i=0;i<Math.min(aa.length,bb.length);i++){if(aa[i]!==bb[i])return aa[i]-bb[i];}return aa.length-bb.length;}
function stableJson(v){if(v===null)return'null';if(v===true)return'true';if(v===false)return'false';if(typeof v==='number')return JSON.stringify(v);if(typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(stableJson).join(',')+']';if(isObject(v))return'{'+Object.keys(v).sort(codePointCompare).map(k=>JSON.stringify(k)+':'+stableJson(v[k])).join(',')+'}';throw new TypeError('unsupported JSON value');}
function sha256Text(s){return `sha256:${sha256Hex(Buffer.from(s,'utf8'))}`;}
function sha256File(file){return `sha256:${sha256Hex(fs.readFileSync(file))}`;}
function filesMap(rows,issues,base='$.files'){const out=new Map();if(!Array.isArray(rows)){issue(issues,base,'files must be array','INVALID_TYPE');return out;}for(const [i,r] of rows.entries()){const p=`${base}[${i}]`;if(!isObject(r)){issue(issues,p,'file entry must be object','INVALID_TYPE');continue;}if(!safeRel(r.path))issue(issues,`${p}.path`,'safe relative POSIX path required','INVALID_PATH');else if(out.has(r.path))issue(issues,`${p}.path`,'duplicate file path','DUPLICATE_VALUE');else out.set(r.path,r);if(!nonEmpty(r.role))issue(issues,`${p}.role`,'role required','MISSING_FIELD');if(!Number.isInteger(r.size)||r.size<0)issue(issues,`${p}.size`,'non-negative integer size required','INVALID_SIZE');if(!DIGEST.test(r.sha256??''))issue(issues,`${p}.sha256`,'sha256 digest required','INVALID_DIGEST');}return out;}
function surfaceProjection(doc,materializationObjects=doc.materialization_objects??[]){const ordered=[...(doc.files??[])].sort((a,b)=>utf8Compare(a?.path??'',b?.path??''));return{format:GITHUB_READ_SURFACE_FORMAT,slug:doc.slug,state_ref:doc.state_ref,state_logical_commitment:doc.state_logical_commitment,entrypoint:doc.entrypoint,files:ordered.map(x=>({path:x.path,role:x.role,size:x.size,sha256:x.sha256})),materialization_objects:materializationObjects};}
export function githubReadSurfaceDigest(doc,materializationObjects=doc.materialization_objects??[]){return sha256Text(canonicalize(surfaceProjection(doc,materializationObjects)));}
export function githubCollectionIndexDigest(rows){return sha256Text(stableJson({format:GITHUB_COLLECTION_INDEX_FORMAT,kristals:rows}));}

export function verifyGithubReadSurface(doc){
 const issues=[];if(!isObject(doc))return{ok:false,issues:[{path:'$',code:'INVALID_TYPE',message:'document must be object'}]};
 if(doc.format!==GITHUB_READ_SURFACE_FORMAT)issue(issues,'$.format',`expected ${GITHUB_READ_SURFACE_FORMAT}`,'UNSUPPORTED_PROFILE');
 if(!nonEmpty(doc.kit_version))issue(issues,'$.kit_version','kit_version required','MISSING_FIELD');if(!nonEmpty(doc.slug)||doc.slug.includes('/')||doc.slug.includes('\\'))issue(issues,'$.slug','single path-segment slug required','INVALID_VALUE');
 if(doc.target_root!==rootForSlug(doc.slug))issue(issues,'$.target_root','target_root must equal kristals/<slug>','RELATION_MISMATCH');if(doc.entrypoint!=='AI_START_HERE.md')issue(issues,'$.entrypoint','AI_START_HERE.md required','INVALID_VALUE');
 if(doc.state_ref!==null&&!nonEmpty(doc.state_ref))issue(issues,'$.state_ref','state_ref must be non-empty or null','INVALID_VALUE');if(doc.state_logical_commitment!==null&&!commitmentOk(doc.state_logical_commitment))issue(issues,'$.state_logical_commitment','valid commitment or null required','INVALID_COMMITMENT');
 if(typeof doc.ready!=='boolean')issue(issues,'$.ready','ready boolean required','INVALID_TYPE');if(!Array.isArray(doc.errors)||doc.errors.some(x=>typeof x!=='string'))issue(issues,'$.errors','errors must be string array','INVALID_TYPE');if(doc.ready===true&&Array.isArray(doc.errors)&&doc.errors.length)issue(issues,'$.errors','ready surface must have no errors','RELATION_MISMATCH');
 if(!DIGEST.test(doc.surface_digest??''))issue(issues,'$.surface_digest','sha256 surface_digest required','INVALID_DIGEST');const map=filesMap(doc.files,issues);const rows=Array.isArray(doc.files)?doc.files:[];
 const sorted=[...rows].sort((a,b)=>utf8Compare(a?.path??'',b?.path??''));if(JSON.stringify(rows.map(x=>x?.path))!==JSON.stringify(sorted.map(x=>x?.path)))issue(issues,'$.files','files must be in deterministic UTF-8 path order','NONDETERMINISTIC_ORDER');
 const total=rows.reduce((n,x)=>n+(Number.isInteger(x?.size)?x.size:0),0);if(doc.file_count!==rows.length)issue(issues,'$.file_count','file_count mismatch','COUNT_MISMATCH');if(doc.total_bytes!==total)issue(issues,'$.total_bytes','total_bytes mismatch','SIZE_MISMATCH');
 if(!Array.isArray(doc.materialization_objects))issue(issues,'$.materialization_objects','materialization_objects must be array','INVALID_TYPE');else if(doc.materialization_object_count!==doc.materialization_objects.length)issue(issues,'$.materialization_object_count','materialization_object_count mismatch','COUNT_MISMATCH');
 for(const req of ['AI_START_HERE.md','AI_MANIFEST.json','ai/INDEX.json'])if(doc.ready===true&&!map.has(req))issue(issues,'$.files',`ready surface missing ${req}`,'MISSING_RESOURCE');
 if(DIGEST.test(doc.surface_digest??'')){const got=githubReadSurfaceDigest(doc);if(got!==doc.surface_digest)issue(issues,'$.surface_digest',`expected ${doc.surface_digest}, got ${got}`,'DIGEST_MISMATCH');}
 return{ok:issues.length===0,issues,surface_digest:doc.surface_digest,state_ref:doc.state_ref};
}

export function verifyGithubSyncManifest(doc){
 const issues=[];if(!isObject(doc))return{ok:false,issues:[{path:'$',code:'INVALID_TYPE',message:'document must be object'}]};if(doc.format!==GITHUB_SYNC_MANIFEST_FORMAT)issue(issues,'$.format',`expected ${GITHUB_SYNC_MANIFEST_FORMAT}`,'UNSUPPORTED_PROFILE');if(doc.read_surface_format!==GITHUB_READ_SURFACE_FORMAT)issue(issues,'$.read_surface_format',`expected ${GITHUB_READ_SURFACE_FORMAT}`,'UNSUPPORTED_PROFILE');
 for(const k of ['manager_version','slug','title','target_root','entrypoint','state_ref'])if(!nonEmpty(doc[k]))issue(issues,`$.${k}`,`${k} required`,'MISSING_FIELD');if(nonEmpty(doc.slug)&&doc.target_root!==rootForSlug(doc.slug))issue(issues,'$.target_root','target_root must equal kristals/<slug>','RELATION_MISMATCH');if(doc.entrypoint!=='AI_START_HERE.md')issue(issues,'$.entrypoint','AI_START_HERE.md required','INVALID_VALUE');if(!commitmentOk(doc.state_logical_commitment))issue(issues,'$.state_logical_commitment','valid commitment required','INVALID_COMMITMENT');if(!DIGEST.test(doc.surface_digest??''))issue(issues,'$.surface_digest','sha256 surface_digest required','INVALID_DIGEST');
 const map=filesMap(doc.files,issues);const rows=Array.isArray(doc.files)?doc.files:[];const sorted=[...rows].sort((a,b)=>utf8Compare(a?.path??'',b?.path??''));if(JSON.stringify(rows.map(x=>x?.path))!==JSON.stringify(sorted.map(x=>x?.path)))issue(issues,'$.files','files must be in deterministic UTF-8 path order','NONDETERMINISTIC_ORDER');const total=rows.reduce((n,x)=>n+(Number.isInteger(x?.size)?x.size:0),0);if(doc.file_count!==rows.length)issue(issues,'$.file_count','file_count mismatch','COUNT_MISMATCH');if(doc.total_bytes!==total)issue(issues,'$.total_bytes','total_bytes mismatch','SIZE_MISMATCH');if(!Number.isInteger(doc.materialization_object_count)||doc.materialization_object_count<0)issue(issues,'$.materialization_object_count','non-negative integer required','INVALID_VALUE');
 if(!map.has(doc.entrypoint))issue(issues,'$.entrypoint','entrypoint must be hosted file','MISSING_RESOURCE');for(const req of ['AI_MANIFEST.json','ai/INDEX.json'])if(!map.has(req))issue(issues,'$.files',`sync manifest missing ${req}`,'MISSING_RESOURCE');
 const policy=doc.policy;if(!isObject(policy))issue(issues,'$.policy','policy object required','INVALID_TYPE');else for(const k of ['derived_read_surface','sync_is_not_publication','activation_is_separate','materialization_blobs_are_not_implicitly_copied'])if(policy[k]!==true)issue(issues,`$.policy.${k}`,'must be true','INVALID_VALUE');
 return{ok:issues.length===0,issues,surface_digest:doc.surface_digest,state_ref:doc.state_ref};
}

export function verifyGithubCollectionIndex(doc){
 const issues=[];if(!isObject(doc))return{ok:false,issues:[{path:'$',code:'INVALID_TYPE',message:'document must be object'}]};if(doc.format!==GITHUB_COLLECTION_INDEX_FORMAT)issue(issues,'$.format',`expected ${GITHUB_COLLECTION_INDEX_FORMAT}`,'UNSUPPORTED_PROFILE');if(!Array.isArray(doc.kristals))issue(issues,'$.kristals','kristals must be array','INVALID_TYPE');const rows=Array.isArray(doc.kristals)?doc.kristals:[];if(doc.count!==rows.length)issue(issues,'$.count','count mismatch','COUNT_MISMATCH');if(!DIGEST.test(doc.index_digest??''))issue(issues,'$.index_digest','sha256 index_digest required','INVALID_DIGEST');
 const paths=new Set(),refs=new Set(),slugs=new Set();for(const [i,r] of rows.entries()){const p=`$.kristals[${i}]`;if(!isObject(r)){issue(issues,p,'entry must be object','INVALID_TYPE');continue;}for(const k of ['slug','title','path','entrypoint','state_ref'])if(!nonEmpty(r[k]))issue(issues,`${p}.${k}`,`${k} required`,'MISSING_FIELD');if(nonEmpty(r.slug)&&r.path!==rootForSlug(r.slug))issue(issues,`${p}.path`,'path must equal kristals/<slug>','RELATION_MISMATCH');if(nonEmpty(r.path)&&r.entrypoint!==`${r.path}/AI_START_HERE.md`)issue(issues,`${p}.entrypoint`,'entrypoint must point to AI_START_HERE.md','RELATION_MISMATCH');if(!commitmentOk(r.state_logical_commitment))issue(issues,`${p}.state_logical_commitment`,'valid commitment required','INVALID_COMMITMENT');if(!DIGEST.test(r.surface_digest??''))issue(issues,`${p}.surface_digest`,'sha256 surface_digest required','INVALID_DIGEST');for(const k of ['file_count','total_bytes','materialization_object_count'])if(!Number.isInteger(r[k])||r[k]<0)issue(issues,`${p}.${k}`,'non-negative integer required','INVALID_VALUE');if(paths.has(r.path))issue(issues,`${p}.path`,'duplicate path','DUPLICATE_VALUE');else paths.add(r.path);if(refs.has(r.state_ref))issue(issues,`${p}.state_ref`,'duplicate state_ref','DUPLICATE_VALUE');else refs.add(r.state_ref);if(slugs.has(r.slug))issue(issues,`${p}.slug`,'duplicate slug','DUPLICATE_VALUE');else slugs.add(r.slug);}
 const sorted=[...rows].sort((a,b)=>utf8Compare(a?.slug??'',b?.slug??'')||utf8Compare(a?.path??'',b?.path??''));if(JSON.stringify(rows)!==JSON.stringify(sorted))issue(issues,'$.kristals','entries must be in deterministic slug/path order','NONDETERMINISTIC_ORDER');if(DIGEST.test(doc.index_digest??'')){const got=githubCollectionIndexDigest(rows);if(got!==doc.index_digest)issue(issues,'$.index_digest',`expected ${doc.index_digest}, got ${got}`,'DIGEST_MISMATCH');}return{ok:issues.length===0,issues,count:rows.length,index_digest:doc.index_digest};
}

function readJson(file,issues,label){try{const v=JSON.parse(fs.readFileSync(file,'utf8'));if(!isObject(v))throw new Error('expected object');return v;}catch(e){issue(issues,label,e.message,'INVALID_JSON');return null;}}
function resolveContained(root,rel){const base=path.resolve(root);const file=path.resolve(base,...rel.split('/'));if(file!==base&&!file.startsWith(base+path.sep))return null;return file;}
export function verifyHostedGithubReadSurface(repoRoot,rootRel){
 const issues=[];if(!safeRel(rootRel)){issue(issues,'$root','safe relative root required','INVALID_PATH');return{ok:false,issues};}const parts=rootRel.split('/');if(parts.length!==2||parts[0]!=='kristals'||parts[1]==='index.json'){issue(issues,'$root','root must be exactly kristals/<slug>','INVALID_PATH');return{ok:false,issues};}const root=resolveContained(repoRoot,rootRel);if(!root||!fs.existsSync(root)||!fs.statSync(root).isDirectory()){issue(issues,'$root','hosted root missing','MISSING_RESOURCE');return{ok:false,issues};}
 const manifest=readJson(path.join(root,SYNC_MANIFEST_REL),issues,SYNC_MANIFEST_REL);if(!manifest)return{ok:false,issues};const mc=verifyGithubSyncManifest(manifest);issues.push(...mc.issues.map(x=>({...x,path:`${SYNC_MANIFEST_REL}${x.path==='$'?'':x.path.slice(1)}`})));if(manifest.target_root!==rootRel)issue(issues,`${SYNC_MANIFEST_REL}.target_root`,'target_root mismatch','RELATION_MISMATCH');
 const map=filesMap(manifest.files,issues,`${SYNC_MANIFEST_REL}.files`);let total=0;for(const [rel,item] of map){const file=resolveContained(root,rel);if(!file||!fs.existsSync(file)||!fs.statSync(file).isFile()){issue(issues,rel,'hosted file missing','MISSING_RESOURCE');continue;}const st=fs.lstatSync(file);if(st.isSymbolicLink()){issue(issues,rel,'symlink not allowed','INVALID_RESOURCE');continue;}if(st.size!==item.size)issue(issues,rel,`expected ${item.size}, got ${st.size}`,'SIZE_MISMATCH');const d=sha256File(file);if(d!==item.sha256)issue(issues,rel,`expected ${item.sha256}, got ${d}`,'DIGEST_MISMATCH');total+=st.size;}
 let stateRel=[...map].find(([,x])=>x.role==='state_snapshot')?.[0];if(!stateRel&&map.has('state/state-snapshot.json'))stateRel='state/state-snapshot.json';if(!stateRel)issue(issues,'state','read surface has no state snapshot','MISSING_RESOURCE');else{const state=readJson(path.join(root,stateRel),issues,stateRel);if(state){const c=verifyStateSnapshot(state);issues.push(...c.issues.map(x=>({...x,path:`${stateRel}${x.path==='$'?'':x.path.slice(1)}`})));if(state.state_ref!==manifest.state_ref)issue(issues,stateRel,'state_ref mismatch','RELATION_MISMATCH');if(JSON.stringify(state.logical_commitment)!==JSON.stringify(manifest.state_logical_commitment))issue(issues,stateRel,'state logical commitment mismatch','RELATION_MISMATCH');}}
 const aiManifest=readJson(path.join(root,'AI_MANIFEST.json'),issues,'AI_MANIFEST.json');if(aiManifest){if(aiManifest.state_ref!==manifest.state_ref)issue(issues,'AI_MANIFEST.json.state_ref','state_ref mismatch','RELATION_MISMATCH');if(JSON.stringify(aiManifest.state_logical_commitment)!==JSON.stringify(manifest.state_logical_commitment))issue(issues,'AI_MANIFEST.json.state_logical_commitment','commitment mismatch','RELATION_MISMATCH');}
 const aiIndex=readJson(path.join(root,'ai/INDEX.json'),issues,'ai/INDEX.json');let materializationObjects=[];if(aiIndex){if(!Array.isArray(aiIndex.files))issue(issues,'ai/INDEX.json.files','files must be array','INVALID_TYPE');else for(const [i,x] of aiIndex.files.entries()){if(!isObject(x)||!safeRel(x.path)){issue(issues,`ai/INDEX.json.files[${i}]`,'invalid file entry','INVALID_PATH');continue;}const hosted=map.get(x.path);if(!hosted)issue(issues,`ai/INDEX.json.files[${i}].path`,'indexed file is outside hosted read surface','MISSING_RESOURCE');else{if(x.size!==undefined&&x.size!==hosted.size)issue(issues,`ai/INDEX.json.files[${i}].size`,'size drift','SIZE_MISMATCH');if(x.sha256&&x.sha256!==hosted.sha256)issue(issues,`ai/INDEX.json.files[${i}].sha256`,'digest drift','DIGEST_MISMATCH');}}materializationObjects=aiIndex.materialization_blobs??[];if(!Array.isArray(materializationObjects)){issue(issues,'ai/INDEX.json.materialization_blobs','must be array','INVALID_TYPE');materializationObjects=[];}if(manifest.materialization_object_count!==materializationObjects.length)issue(issues,`${SYNC_MANIFEST_REL}.materialization_object_count`,'materialization count mismatch','COUNT_MISMATCH');}
 if(DIGEST.test(manifest.surface_digest??'')){const pseudo={...manifest,format:GITHUB_READ_SURFACE_FORMAT,files:[...map.values()],materialization_objects:materializationObjects};const got=githubReadSurfaceDigest(pseudo,materializationObjects);if(got!==manifest.surface_digest)issue(issues,`${SYNC_MANIFEST_REL}.surface_digest`,`expected ${manifest.surface_digest}, got ${got}`,'DIGEST_MISMATCH');}
 const allowed=new Set([...map.keys(),SYNC_MANIFEST_REL]);function walk(dir,prefix=''){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const rel=prefix?`${prefix}/${ent.name}`:ent.name;const full=path.join(dir,ent.name);const lst=fs.lstatSync(full);if(lst.isSymbolicLink())issue(issues,rel,'symlink not allowed','INVALID_RESOURCE');else if(lst.isDirectory())walk(full,rel);else if(lst.isFile()&&!allowed.has(rel))issue(issues,rel,'unmanaged file under exact read surface','UNMANAGED_RESOURCE');}}walk(root);
 if(manifest.total_bytes!==total)issue(issues,`${SYNC_MANIFEST_REL}.total_bytes`,`expected ${manifest.total_bytes}, got ${total}`,'SIZE_MISMATCH');return{ok:issues.length===0,issues,root:rootRel,state_ref:manifest.state_ref,surface_digest:manifest.surface_digest,file_count:map.size,total_bytes:total};
}

export function verifyHostedGithubCollection(repoRoot){
 const issues=[];const indexFile=path.join(path.resolve(repoRoot),...INDEX_REL.split('/'));if(!fs.existsSync(indexFile))return{ok:true,issues:[],count:0,status:'not-yet-created'};const index=readJson(indexFile,issues,INDEX_REL);if(!index)return{ok:false,issues};const ic=verifyGithubCollectionIndex(index);issues.push(...ic.issues.map(x=>({...x,path:`${INDEX_REL}${x.path==='$'?'':x.path.slice(1)}`})));for(const [i,row] of (Array.isArray(index.kristals)?index.kristals:[]).entries()){if(!isObject(row)||!safeRel(row.path))continue;const manifestFile=path.join(path.resolve(repoRoot),...row.path.split('/'),...SYNC_MANIFEST_REL.split('/'));const m=readJson(manifestFile,issues,`${row.path}/${SYNC_MANIFEST_REL}`);if(m){if(m.state_ref!==row.state_ref)issue(issues,`${INDEX_REL}.kristals[${i}].state_ref`,'index/manifest state_ref drift','RELATION_MISMATCH');if(m.surface_digest!==row.surface_digest)issue(issues,`${INDEX_REL}.kristals[${i}].surface_digest`,'index/manifest surface digest drift','RELATION_MISMATCH');if(JSON.stringify(m.state_logical_commitment)!==JSON.stringify(row.state_logical_commitment))issue(issues,`${INDEX_REL}.kristals[${i}].state_logical_commitment`,'index/manifest commitment drift','RELATION_MISMATCH');if(row.entrypoint!==`${row.path}/${m.entrypoint}`)issue(issues,`${INDEX_REL}.kristals[${i}].entrypoint`,'index/manifest entrypoint drift','RELATION_MISMATCH');if(row.file_count!==m.file_count||row.total_bytes!==m.total_bytes||row.materialization_object_count!==m.materialization_object_count)issue(issues,`${INDEX_REL}.kristals[${i}]`,'index/manifest stats drift','RELATION_MISMATCH');}const hc=verifyHostedGithubReadSurface(repoRoot,row.path);issues.push(...hc.issues.map(x=>({...x,path:`${row.path}/${x.path}`})));}return{ok:issues.length===0,issues,count:Array.isArray(index.kristals)?index.kristals.length:0,index_digest:index.index_digest};
}
